language: java
#
jdk:
- openjdk7
- oraclejdk7
env:
  matrix:
  - TERM=dumb
  global:
    secure: j7V7/RvXHLu+O5RvQVclggUelopNpmftqtsxYOY3sQTez2fxhrxqB8jZ2CVw089elSz8NH37JBoqQYm3TN/LPN2aozOgiriYX1ubCpTMj74ideb0om5ZkFue6BBFrtL1E5UZjRttO7QT+YZMhfQdJvlxZYsFtTiQl5Ypks6rBUc=
install:
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- heroku auth:login email
- heroku labs:enable pipelines
- heroku plugins:install git://github.com/heroku/heroku-pipeline.git
before_script:
- "./bin/travis/build"
script:
- "./bin/travis/unit_test"
deploy:
  provider: heroku
  api_key:
    secure: J4lzvTe1LK+8XY9JKhsSzTuUGt3eNG395/ZH6gQ5JEOr31QztazUP4L8KNu/u8IoM3HPuF+gZKUnTJufDl9mDN4tsWYx5HQlPKUGSg7J2l7AluJERiUCQ/YXzJNYxvY17Bc/UNrbdOMQ9Ma7+zcjnwxCiAFTWcIBKo6e9kN/0mM=
  app: nerdir-staging
  strategy: git
  on:
    repo: NerdirMedSkapgerdir/TicTacToe
after_deploy:
- "./bin/travis/test_and_promote"
