language: java
jdk:
- openjdk7
- oraclejdk7

env:  
  global:
    - TERM=dumb
    - secure: "AAcd722e1XF6uE/sCyHyunlWe4/Eu17LBo8vIxXnwSvP+AJVaJm2zszqXY7nhggLXOWSu19yVIPpXpl3nq4oP1j6KZei7TdCgQKMce6Ii9Wt2lfmjZ8cpi8scZtnh8lB31uC0iHuKhIGjOnvZkkEtf+HXALpADLOWuKi0zCEdO0="

script: 
- "./gradlew clean" 
- "./gradlew check" 
- "./gradlew build" 
- "./gradlew test" 
- "./gradlew jacocoTestReport coveralls"

after_script:
addons:
  coverity_scan:
    project:
      name: "NerdirMedSkapgerdir/TicTacToe"
      description: "Build submitted via Travis CI"
    notification_email: bergthor13@ru.is
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan

deploy:
  provider: heroku
  api_key:
    secure: GbOepOMObba4FeSPJZQtXWTHKbqp0mzNEijXrI6K4V6XfFeJKcxG0CP0wFv1BgemKN8sCTBQhMif6s8+kvuRPgboOK9vymF1cPZSCIS1L4AZD6aOzgOPzCNPzwlKsprgkoQvRhXPL7kFiORdR7etZTCtrzW3s3/4YTd+nkyl57A=
  app: nerdir
  on:
    repo: NerdirMedSkapgerdir/TicTacToe
after_deploy:
- "./gradlew seleniumXvfb"


