language: java
jdk:
- openjdk7
- oraclejdk7
env:
- TERM=dumb
script:
- "./bin/clean"
- "./bin/check"
- "./bin/build"
after_success:
- "./bin/unit_test"
- "./gradlew jacocoTestReport coveralls"
after_success:
deploy:
  provider: heroku
  api_key:
    secure: GbOepOMObba4FeSPJZQtXWTHKbqp0mzNEijXrI6K4V6XfFeJKcxG0CP0wFv1BgemKN8sCTBQhMif6s8+kvuRPgboOK9vymF1cPZSCIS1L4AZD6aOzgOPzCNPzwlKsprgkoQvRhXPL7kFiORdR7etZTCtrzW3s3/4YTd+nkyl57A=
  app: nerdir
  on:
    repo: NerdirMedSkapgerdir/TicTacToe
after_deploy:
- "./gradlew seleniumXvfb"


