/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'arnar' at '10/24/14 3:38 PM' with Gradle 2.1
 *
 * @author arnar, @date 10/24/14 3:38 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
